Modem fixes
dosbox-staging/dosbox-staging pull request #1464
Opened 2021-12-25 16:43 UTC by NicknineTheEagle

* Actually use modem registers for setting CR, LF and BS chars.
* Ignore escape char (+) when at the start of modem command (i.e. when the buffer is empty). This fixes The Need for Speed which sends "+++AT" to the modem at init time.

2021-12-25 21:59 UTC, kcgen commented
Thanks @NicknineTheEagle; these are notable games and certainly want them working.

Can you split the addition of the echo() function (and calling it) into a separate commit? 

This main reason is to make the three concepts in this PR compartmentalized easy to bisect, if needed.

If your modem regression testing is coming back positive, then will be happy to merge.

2021-12-25 22:04 UTC, kcgen commented
(out of scope, but just mentioning it)

Regarding the thee +++'s or three escapes prior to AT:

> That's the "Escape Sequence" that switches the modem from data to command state, which usually disconnects modem.; this command is not proceeded by AT. Most modems have a "guard time" of 1 second in which no additional data should be sent to the modem before or after the escape code is sent, or it will be ignored. 

---

I'm not sure if the code current checks for the "quiet time" before and after the escape sequence is received as criteria to switch to command mode.. but that would be another welcome feature. 👍

2021-12-26 14:13 UTC, NicknineTheEagle commented
> (out of scope, but just mentioning it)
> 
> Regarding the thee +++'s or three escapes prior to AT:
> 
> > That's the "Escape Sequence" that switches the modem from data to command state, which usually disconnects modem.; this command is not proceeded by AT. Most modems have a "guard time" of 1 second in which no additional data should be sent to the modem before or after the escape code is sent, or it will be ignored.
> 
> I'm not sure if the code current checks for the "quiet time" before and after the escape sequence is received as criteria to switch to command mode.. but that would be another welcome feature. 👍

I'm aware of what +++ is, the issue is that games often can't know for certain if modem is in command mode so they'll send +++ before firing commands. Real modem is supposed to ignore those in command mode.

2021-12-26 17:57 UTC, kcgen commented
@NicknineTheEagle> (tested) Doom, Descent, The Need for Speed, Duke Nukem 3D. Duke 3D connects fine but crashes in-game, this issue came all the way from SVN.  This happens in UDP mode, too, which furthers my suspicions that the crash has nothing to do with modem emulation.

Thanks for elaborating on your testing @NicknineTheEagle. Your PR is working much better in 688 Attack Sub as well:

![2021-12-26_09-54](https://user-images.githubusercontent.com/1557255/147416268-ea5bd5bf-bb57-4267-b22e-6967f7f52eff.png)

2021-12-26 21:18 UTC, kcgen commented on src/hardware/serialport/softmodem.cpp
> +
:+1: - looks good - and thanks for keeping the interface "8-bit clean".

2021-12-27 01:49 UTC, kcgen commented on src/hardware/serialport/softmodem.cpp
> +							socketType ? "ENet" : "TCP");
For the two indented lines that are part of LOG_MSG: `GetPortNumber(),` and `socketType ...`

Can you tab them inward up to the same level as the `LOG_MSG`, and from there, space them inward until they line up with the first double-quote `"` in `"SERIAL`.

This way, muilti-line alignment for fuinction arguments will always be lined up, regardless of tab-size.

If you have clang-format, you can run `./scripts/format-commit.sh` or `git clang-format`, both of which will just apply formatting clean rules (like this) automatically to any changed lines in the current commit.  It's very handy for fixing stuff like this.  I think vscode and Visual Studio can auto-apply it too.

2021-12-27 02:08 UTC, kcgen requested changes
Just one minor whitespace comment; nothing else after that. 
Thank you @NicknineTheEagle !

2021-12-27 02:43 UTC, kcgen approved these changes
Adding to backports for 0.78.x

2021-12-27 02:44 UTC, merged