-v bash_completion conflict with loguru verbosity
dosbox-staging/dosbox-staging pull request #1475
Opened 2021-12-29 02:26 UTC by arrowgent

`dosbox -v` currently controls loguru verbosity
its not defined for equivalent `--version`

2021-12-29 02:59 UTC, arrowgent commented
https://github.com/dosbox-staging/dosbox-staging/pull/1475

2021-12-29 22:54 UTC, kcgen requested changes
Can you PR this to the dosbox-staging/loguru repo?

This is "upstream", and will make sure this change is not lost when we copy over new updates from that repo.

It will also let us push that change further upstream to the original repo for the author to consider.

2021-12-29 22:55 UTC, kcgen commented on src/gui/gui_msgs.h
> +  --version       Output version information and exit.
Looks good :+1:

2021-12-29 22:57 UTC, kcgen requested changes
Thanks @arrowgent !

Only two changes - please move the Loguru commit to that repo (https://github.com/dosbox-staging/loguru), and remove that commit this this PR.  Reason is, we copy from that upstream repo and we don't edit our local file here.. it's overwritten/clobbered by the upstream.

Second: please update the commit messages to follow "the imperative" style, or "command style" phrasing. Tips here:   https://github.com/dosbox-staging/dosbox-staging/blob/main/CONTRIBUTING.md#commit-messages

You can see

2021-12-30 00:13 UTC, arrowgent commented
you have no idea how difficult it is to find any way to revert a commit in the browser of github
or a way to remove a commit from this PR ha

2021-12-30 00:41 UTC, arrowgent commented
madness.  some simple features through a browser are limited to other tools (cli)
https://github.blog/2014-06-24-introducing-the-revert-button/

closing and remaking the PR to get rid of my fiddling around

2021-12-30 00:41 UTC, closed without merging

2021-12-30 01:25 UTC, kcgen commented
I'm very sorry for putting you through that. I didn't realize you were using the web UI. 
I am very happy to help on my side and still attribute the commits to you - if that works. Just shout.

2021-12-30 02:24 UTC, arrowgent commented
no worries.  i should get onboard with using my terminal skills for managing git one of these days!

2021-12-30 07:03 UTC, Wengier commented
I used the web UI in the beginning too, before getting to use Git command.

2021-12-30 10:02 UTC, Grounded0 commented
https://www.sublimemerge.com/

My choice.