Add compile-time flag for experimental Voodoo support
dosbox-staging/dosbox-staging pull request #2399
Opened 2023-04-12 08:22 UTC by dreamer

No code yet, just a disabled compilation flag to be used during development.

Once 3dfx support will be complete and tested and stable, we'll remove the feature flag.

2023-04-12 08:57 UTC, ThomasEricB commented
Wonderful news! I'll review it right away!

2023-04-12 09:41 UTC, ThomasEricB requested changes
So, I've `git grep` the code for the other C_* and I'm wondering... Isn't a change on dosbox.cpp missing? Something like this:

```
#if C_VOODOO
	VOODOO_AddConfigSection(control); // I know that VOODOO_AddConfigSection doesn't exist, just an example 
#endif
```

Or like the additions done by this commit? https://github.com/dosbox-staging/dosbox-staging/commit/bc48835e275c74fa5a237ffe64d35249b7390874#diff-f5ea1ed765f6d313041204e8564ce84ca2dc2c94255c6ad4d92f933d0fe723e4

2023-04-12 18:07 UTC, kcgen commented
@dreamer , maybe this should be paired with the PR that brings in the initial (and experimental) batch of voodoo to `main`?

Another way of wording it is that this meson flag should depend on the presence of the experimental code to build.

2023-04-13 08:01 UTC, dreamer commented
Hmm, that means I will need to start splitting out some functional parts of kekko's original code... I don't want to merge in any actual voodoo emulation yet. I think @ThomasEricB idea is good - we can limit the changes to .conf section for now, maybe a few other lines.

2023-04-14 07:14 UTC, kcgen commented
I'm just hesitant to merge the cart before the horse. 

We have plans to add AWE32 and SC55 when they're ready on day in months or years to come, and similarly we're not adding conf, meson toggles, or C_FEATURE until there's functional code backing those up. 

I think it makes sense to bring in this PR's voodoo-experimental toggle when there's some basic voodoo functionality to experiment with (sufficiently passing CI and the sanitizers)

2023-04-14 07:46 UTC, closed without merging