Avoid a TSAN issue in SDL by using DOSBox's PIC timer to animate the `[● REC]` animation
dosbox-staging/dosbox-staging pull request #3932
Opened 2024-09-15 03:45 UTC by interloper98

# Description

When investigating TSAN issues relating to audio and video capture, @weirddan455 figured out that some of my issues were coming from SDL's threaded timer handling used by the titlebar animation.

The titlebar animation is fine, but it's SDL threaded timer that has some non-trivial internatls (and it's in there where the TSAN data races exist):

```
WARNING: ThreadSanitizer: data race (pid=21888)
  Read of size 4 at 0x000001963320 by main thread (mutexes: write M0):
    #0 SDL_AtomicTryLock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:75
    #1 SDL_AtomicLock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:176
    #2 SDL_AddTimer_REAL ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:283
    #3 SDL_AddTimer ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:519
    #4 maybe_start_animation ../../src/gui/titlebar.cpp:154
    #5 GFX_RefreshTitle() ../../src/gui/titlebar.cpp:387
    #6 GFX_NotifyVideoCaptureStatus(bool) ../../src/gui/titlebar.cpp:418
    #7 CAPTURE_StartVideoCapture() ../../src/capture/capture.cpp:370
    #8 handle_capture_video_event ../../src/capture/capture.cpp:567
    #9 CHandlerEvent::Active(bool) ../../src/gui/sdl_mapper.cpp:1855
    #10 CTriggeredEvent::ActivateEvent(bool, bool) ../../src/gui/sdl_mapper.cpp:158
    #11 CBind::ActivateBind(long, bool, bool) ../../src/gui/sdl_mapper.cpp:274
    #12 CBindGroup::ActivateBindList(std::__debug::list<CBind*, std::allocator<CBind*> >*, long, bool) ../../src/gui/sdl_mapper.cpp:1432
    #13 CKeyBindGroup::CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:450
    #14 MAPPER_CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:2783
    #15 GFX_Events() ../../src/gui/sdlmain.cpp:4165
    #16 Normal_Loop ../../src/dosbox.cpp:188
    #17 DOSBOX_RunMachine() ../../src/dosbox.cpp:450
    #18 CALLBACK_RunRealInt(unsigned char) ../../src/cpu/callback.cpp:117
    #19 device_CON::Read(unsigned char*, unsigned short*) ../../src/dos/dev_con.h:89
    #20 DOS_Device::Read(unsigned char*, unsigned short*) ../../src/dos/dos_devices.cpp:329
    #21 DOS_ReadFile(unsigned short, unsigned char*, unsigned short*, bool) ../../src/dos/dos_files.cpp:665
    #22 DOS_Shell::ReadCommand[abi:cxx11]() ../../src/shell/shell_misc.cpp:140
    #23 DOS_Shell::InputCommand(char*) ../../src/shell/shell_misc.cpp:79
    #24 DOS_Shell::Run() ../../src/shell/shell.cpp:492
    #25 SHELL_Init() ../../src/shell/shell.cpp:1430
    #26 Config::StartUp() ../../src/misc/setup.cpp:1669
    #27 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5046
    #28 main ../../src/main.cpp:30

  Previous atomic write of size 4 at 0x000001963320 by thread T1:
    #0 SDL_AtomicUnlock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:190
    #1 SDL_TimerThread ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:130
    #2 SDL_RunThread ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:333
    #3 RunThread ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_systhread.c:76

  Location is global 'SDL_timer_data' of size 208 at 0x000001963280

  Mutex M0 (0x720c00000c00) created at:
    #0 pthread_mutex_init ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1315 (libtsan.so.2+0x58bfd) (BuildId: 64c1e8de04b11a7d960abd7e45f94f3b277b7779)
    #1 SDL_CreateMutex_REAL ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_sysmutex.c:58
    #2 SDL_AtomicTryLock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:72
    #3 SDL_AtomicLock_REAL ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:176
    #4 SDL_GetErrBuf ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:275
    #5 SDL_ClearError_REAL ../../subprojects/SDL2-2.30.6/src/SDL_error.c:72
    #6 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:222
    #7 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:217
    #8 SDL_Init_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:394
    #9 SDL_Init ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:88
    #10 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:4921
    #11 main ../../src/main.cpp:30

  Thread T1 'SDLTimer' (tid=21890, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1022 (libtsan.so.2+0x5a267) (BuildId: 64c1e8de04b11a7d960abd7e45f94f3b277b7779)
    #1 SDL_SYS_CreateThread ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_systhread.c:116
    #2 SDL_CreateThreadWithStackSize_REAL ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:401
    #3 SDL_CreateThreadInternal ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:452
    #4 SDL_TimerInit ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:227
    #5 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:256
    #6 SDL_InitSubSystem_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:217
    #7 SDL_Init_REAL ../../subprojects/SDL2-2.30.6/src/SDL.c:394
    #8 SDL_Init ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:88
    #9 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:4921
    #10 main ../../src/main.cpp:30

SUMMARY: ThreadSanitizer: data race ../../subprojects/SDL2-2.30.6/src/atomic/SDL_spinlock.c:75 in SDL_AtomicTryLock_REAL
==================
==================
WARNING: ThreadSanitizer: data race (pid=21888)
  Read of size 8 at 0x000001963330 by main thread:
    #0 SDL_AddTimer_REAL ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:329
    #1 SDL_AddTimer ../../subprojects/SDL2-2.30.6/src/dynapi/SDL_dynapi_procs.h:519
    #2 maybe_start_animation ../../src/gui/titlebar.cpp:154
    #3 GFX_RefreshTitle() ../../src/gui/titlebar.cpp:387
    #4 GFX_NotifyVideoCaptureStatus(bool) ../../src/gui/titlebar.cpp:418
    #5 CAPTURE_StartVideoCapture() ../../src/capture/capture.cpp:370
    #6 handle_capture_video_event ../../src/capture/capture.cpp:567
    #7 CHandlerEvent::Active(bool) ../../src/gui/sdl_mapper.cpp:1855
    #8 CTriggeredEvent::ActivateEvent(bool, bool) ../../src/gui/sdl_mapper.cpp:158
    #9 CBind::ActivateBind(long, bool, bool) ../../src/gui/sdl_mapper.cpp:274
    #10 CBindGroup::ActivateBindList(std::__debug::list<CBind*, std::allocator<CBind*> >*, long, bool) ../../src/gui/sdl_mapper.cpp:1432
    #11 CKeyBindGroup::CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:450
    #12 MAPPER_CheckEvent(SDL_Event*) ../../src/gui/sdl_mapper.cpp:2783
    #13 GFX_Events() ../../src/gui/sdlmain.cpp:4165
    #14 Normal_Loop ../../src/dosbox.cpp:188
    #15 DOSBOX_RunMachine() ../../src/dosbox.cpp:450
    #16 CALLBACK_RunRealInt(unsigned char) ../../src/cpu/callback.cpp:117
    #17 device_CON::Read(unsigned char*, unsigned short*) ../../src/dos/dev_con.h:89
    #18 DOS_Device::Read(unsigned char*, unsigned short*) ../../src/dos/dos_devices.cpp:329
    #19 DOS_ReadFile(unsigned short, unsigned char*, unsigned short*, bool) ../../src/dos/dos_files.cpp:665
    #20 DOS_Shell::ReadCommand[abi:cxx11]() ../../src/shell/shell_misc.cpp:140
    #21 DOS_Shell::InputCommand(char*) ../../src/shell/shell_misc.cpp:79
    #22 DOS_Shell::Run() ../../src/shell/shell.cpp:492
    #23 SHELL_Init() ../../src/shell/shell.cpp:1430
    #24 Config::StartUp() ../../src/misc/setup.cpp:1669
    #25 sdl_main(int, char**) ../../src/gui/sdlmain.cpp:5046
    #26 main ../../src/main.cpp:30

  Previous write of size 8 at 0x000001963330 by thread T1:
    #0 SDL_TimerThread ../../subprojects/SDL2-2.30.6/src/timer/SDL_timer.c:122
    #1 SDL_RunThread ../../subprojects/SDL2-2.30.6/src/thread/SDL_thread.c:333
    #2 RunThread ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_systhread.c:76

  Location is global 'SDL_timer_data' of size 208 at 0x000001963280

  Thread T1 'SDLTimer' (tid=21890, running) created by main thread at:
    #0 pthread_create ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1022 (libtsan.so.2+0x5a267) (BuildId: 64c1e8de04b11a7d960abd7e45f94f3b277b7779)
    #1 SDL_SYS_CreateThread ../../subprojects/SDL2-2.30.6/src/thread/pthread/SDL_systhread.c:116
    #2 SDL_CreateThreadWithStackSiz [...]

2024-09-15 03:49 UTC, interloper98 commented
Thanks, @weirddan455, for figuring out that this specific TSAN issue originated in the non-trivial depths of SDL :dragon_face:

2024-09-15 05:34 UTC, weirddan455 commented
Yeah, moving it to a PIC event is one way to address the issue.  I believe @FeralChild64 wrote this title bar code so maybe so if he has any thoughts on this.

One minor issue I can think of is this moves from wall clock time to emulated time.  For example, if you hit the fast-forward hotkey (ALT + F12) you probably see the animation move very quickly.  Probably not a big deal for this use-case but something to keep in mind.

All that said, I think this is a fine approach.  I question sometimes whether these TSAN warnings are actually justified but the comments in the SDL code don't inspire much confidence.  This is where you were getting the warning (non-atomic read on the `lock` variable).  It's guarded by a mutex but the writer to that variable is not and it should probably be an atomic read (if such a thing is possible in C89).

```c
/* This function is where all the magic happens... */
SDL_bool SDL_AtomicTryLock(SDL_SpinLock *lock)
{
#ifdef SDL_ATOMIC_DISABLED
    /* Terrible terrible damage */
    static SDL_mutex *_spinlock_mutex;

    if (!_spinlock_mutex) {
        /* Race condition on first lock... */
        _spinlock_mutex = SDL_CreateMutex();
    }
    SDL_LockMutex(_spinlock_mutex);
    if (*lock == 0) {
        *lock = 1;
        SDL_UnlockMutex(_spinlock_mutex);
        return SDL_TRUE;
    } else {
        SDL_UnlockMutex(_spinlock_mutex);
        return SDL_FALSE;
    }
```

2024-09-15 07:34 UTC, FeralChild64 commented
> One minor issue I can think of is this moves from wall clock time to emulated time. For example, if you hit the fast-forward hotkey (ALT + F12) you probably see the animation move very quickly

That's precisely why I have decided not to use the PIC timers - IMHO GUI animation pacer shouldn't be mixed with the emulation pacer, ever.
If there are problems with SDL timers, I would suggest to replace them with some kind of `std::thread` + `std::chrono` solution.

2024-09-15 10:18 UTC, johnnovak commented
> One minor issue I can think of is this moves from wall clock time to emulated time.

Yeah, apart from the conceptual wrongness of using the emulated PIC timer to do all sorts of things it was never intended to do in a real PC 😆 Overloading the PIC timers with all sorts of extra stuff apart from their real job might also introduce weird lags in the emulation and it just results in a mess.

Abusing the PIC timer to do emulation-related stuff that never happens on real hardware is one thing (e.g., we do that for various VGA drawing related delays). It's absolutely a hack, though, and it should never have been done in the first place.

But this is next level; this change abuses the PIC timer to time non-emulation related stuff.  We definitely should _not_ do that.

Can you please rework this to use a completely separate wall clock based timing method unrelated to the emulation?

I approved the previous PR that used the PIC timer for the AUTOTYPE command as that was kinda OK and it makes sense to tie the autotype speed to the emulation time.

I think this should be our approach going forward:

1. Introduce a secondary "fake PIC timer" to handle emulation-related internal timings currently farmed out to the real PIC timer (e.g., autotype, VGA timings/delays, etc.)

2. The real PIC timer then should only do what it does on hardware and nothing else.

3. For any other timings that operate not in emulation time but wall clock time (e.g., the blinking recording indicator), we must use other timing methods using SDL, C++ stdlib calls, host OS APIs, or whatever.

> That's precisely why I have decided not to use the PIC timers - IMHO GUI animation pacer shouldn't be mixed with the emulation pacer, ever.
If there are problems with SDL timers, I would suggest to replace them with some kind of std::thread + std::chrono::steady_clock solution.

Yeah, exactly. The previous approach was fine, just try to make it more robust, or ignore TSAN warnings altogether if they're false positives or "theorethical" possibilities.

2024-09-15 15:25 UTC, interloper98 commented
Here's the approach I'm thinking of:
 - Let you scheduling a callback to be run in the future, either one-shot or repeating (similar to PIC)
 - Let you remove the callback(s) (similar to PIC)
 - Granularity will only be at the millisecond level

Internals:
 - Will make use of `timer.h`'s `Get...()` calls, which use `chrono::steady_clock`  
 - Callbacks that have come due will run after the core loop (similar to SDL processing it's event queue)
 - Will use <functional> so that class member functions (binds) and 'pure' lamdas can be scheduled, too. This is a bit better than the PIC, because binds cannot be scheduled.

Should be pretty small and near-zero cost (when things aren't scheduled) just enough code to support this titlebar and AUTOTYPE (which I'll move).

I'll start chipping away; let me know if there are other ideas or problems/gotchas you see with this.

2024-09-15 16:18 UTC, weirddan455 commented
So basically an event subsystem that uses real time instead of emulated ticks?  It sounds fine in theory.  It avoids potential threading pitfalls and coupling with SDL's timer.

Maybe a bit overkill though?  Unclear if it's better to have autotype use real time or emulated time (I guess it was real time before your recent change with a janky custom threaded solution).  The only use case for SDL's timer is the title bar and my PR #3934 fixes the TSAN warning by enabling SDL's atomics.

I don't want to discourage you from improving things but I'm not sure if building out a whole event system for animating a title bar is exactly worth it.  Maybe there's some other places where this could be useful but I can't think of any at the moment.

Go ahead and write the code if you feel so inclined though.

2024-09-15 16:35 UTC, interloper98 commented
> So basically an event subsystem that uses real time instead of emulated ticks? 

Yes :+1: It's just a "run this function in the future". 

(Where as SDL was more like "Run this function in the future, and oh, by the way, the function will be run on a thread so don't try to make changes in your SDL objects like the titlebar because it'll break!")

> Maybe a bit overkill though? 

It'll be a container holding callbacks, and loop through (0 or more) of them.

If the callback's time has "come due", then it's run.

That's as simple as I can go - but maybe it can be simpler (let me know!)

2024-09-15 19:48 UTC, johnnovak commented
I appreciate your ideas @interloper98, and I agree, an eventing subsystem you outlined would be ideal if we'd need to deal with a lot of non-emulation related timed events... but that's not the case, as you correctly identified.

I'm with @weirddan455 here; introducing a whole eventing subsystem for a single use case, the blinking recording indicator, would be an _enormously massive_ overkill. I cannot think of any other use of timed events in the foreseeable future.

We most certainly should not introduce complex subsystem for a sample size of one, so let's go with @weirddan455's solution (nice find, man! 🏅)

In the OSD I will need to display messages with timeouts (e.g., notifications), but as the OSD will be rendered at a steady FPS, like a game engine, all such timings will boil down to calculating delta times where necessary per frame which can be trivially implemented in an ad hoc manner in a couple of spots in the OSD drawing routines -- no eventing system needed either.

2024-09-15 19:50 UTC, johnnovak requested changes
I appreciate the effort @interloper98, but let's go with @weirddan455's solution to get rid of the TSAN warnings. The current implementation is fine.

2024-09-15 19:58 UTC, johnnovak commented
> Should be pretty small and near-zero cost (when things aren't scheduled) just enough code to support this titlebar and AUTOTYPE (which I'll move).

Yeah, so like I said, I actually prefer emulation time for AUTOTYPE, so nothing to do there either for now.

2024-09-15 20:41 UTC, interloper98 commented
There's audio callbacks keeping SDL's host-side audio output fed, because the host mixer is draining at host time, no matter what.

That's one of the first abuses of the PIC callback system.

I'm happy not implementing this host-side / wall clock callback loop.

In which case: then we're OK with using the PIC system to update the title bar every 750ms?

(This was a damned if you do, damned if you don't scenario.. if we're going to be OK with using PIC, then so be it, let's do it eyes wide open 😂)

2024-09-15 20:44 UTC, closed without merging

2024-09-15 20:52 UTC, weirddan455 commented
>  There's audio callbacks keeping SDL's host-side audio output fed, because the host mixer is draining at host time, no matter what.
>
>  That's one of the first abuses of the PIC callback system.

That's no longer the case since my threaded mixer PR.  The rate at which the mixer itself runs is entirely async from the emulator core now.  The remaining uses for PIC callbacks for audio are running at a fixed once per emulated tick rate and will break if changed.  Best example is PC Speaker which was written with an assumption that its callback runs exactly every tick and sounds distorted if that assumption is broken.  I'm going to be looking at threading those individual audio devices after 0.82.0 releases to get them off the PIC queue entirely.

>  In which case: then we're OK with using the PIC system to update the title bar every 750ms?

I think @johnnovak is saying we should stick with the SDL timer for the title bar.

2024-09-15 21:01 UTC, interloper98 commented
Yeah, it's just a question of host side vs emulation side. If those audio devices need emulation-side timing then PIC is 100% the right use.

Is the mixer's capture timer host side, too? Just a question, I'm not trying to be argumentative.  I just remembered a bunch of comments about "pic abuse" and figured we could mop those all up and fix it. But if not --  Cool, we don't need it. 

I'm just trying to see if the titlebar is really the only thing in the entire codebase that we're driving at host-side timing.

(If so.. then yeah, let's wait until more uses appear before creating a solution).

2024-09-15 21:20 UTC, weirddan455 commented
>  Is the mixer's capture callback timer host side or emu side?

That is a PIC callback and could probably be lopped in with the "PIC abuse" comments.  I would like to make capture threaded as well after 0.82.0.  It would be pretty trivial to do for audio capture but more tricky for video since the audio needs to sync with the video on the main thread.  It's on my TODO list though.

2024-09-15 21:26 UTC, interloper98 commented
>  I would like to make capture threaded as well after 0.82.0 (and therefore not timer based at all)

Right on, and thanks for explaining the future plans, too. All sounds good, and I agree it makes the most sense to close this until a need arises.

2024-09-16 06:46 UTC, johnnovak commented
> > Is the mixer's capture callback timer host side or emu side?
> 
> That is a PIC callback and could probably be lopped in with the "PIC abuse" comments. I would like to make capture threaded as well after 0.82.0 (and therefore not timer based at all). It would be pretty trivial to do for audio capture but more tricky for video since the audio needs to sync with the video on the main thread. It's on my TODO list though.

@interloper98 @weirddan455 
To be clear, I wasn't saying never use emulator time based timing for anything.

What I was saying is to use the PIC (Programmable Interrupt Controller implemented in `pic.h`) only for what it does in a real PC and nothing more.

Then technically make a copy of `pic.h` as `timer.h` or something, get rid of the actual PIC controller related details and only leave the few delayed/recurring timing related functions that the "PIC abuse" code fragments use. Then change all "PIC abuse" code to use `timer.h`.

The result: `pic.h` is only used for emulating the real PIC chip, and `timer.h` (`TIMER_*` function calls) are used for all other emulation time based timings that have nothing to do with PIC emulation.

This would be more of a conceptual cleanup as the executed code would be mostly the same (at least in the first iteration of this separation).