Always support Opus CD-DA tracks
dosbox-staging/dosbox-staging pull request #928
Opened 2021-03-05 15:58 UTC by kcgen

Vorbis has been deprecated for years by its maintainer Xiph who recommends Opus as its successor because it provides:
 - superior audio qualilty at lower bitrates
 - PCM-accurate seeking
 - very low block-level latency

One of the reasons Staging supports Opus is to allow those packaging games (like GoG) to finally get off Vorbis once and for all.

However, if Staging makes Opus optional for package maintainers then why would anyone packaging games rely on Opus.

This commit make Opus no longer optional. We know Opus is supported under all known repositories that we ever expect Staging to run on, and even beyond that we know Opus can be  compiled on all platforms as well.

2021-03-05 16:07 UTC, kcgen commented
@dreamer , 

I was testing CD-DA latency and found my usual Opus CDROM images weren't mounting.  This is despite Meson reporting the Opus codecs. 

```
MAIN: Draw resolution: 640x400, pixel aspect ratio: 1.20
IMGMOUNT: Path 'cd/opus/cdrom.cue' found
MIXER: CDAUDIO channel operating at 44100 Hz without resampling
CDROM: Failed adding 'track02.opus' as CDDA track!
CDROM: can't read audio because requested offset 32768 is beyond the track length, 4120
CDROM: can't read audio because requested offset 37648 is beyond the track length, 4120
CDROM: can't read audio because requested offset 37400 is beyond the track length, 4120
CDROM: can't read audio because requested offset 37656 is beyond the track length, 4120
```


I've been testing Opus on every known platform - PPC big-endian, ARM, macOS VM, Window, BSD (helloSystems), and even my SunSparc back when I had it setup. 

So, seeing that we're still going to such a great effort to exclude Opus (and to have it not even work on my x86-64) bothered me unfortunately more that it probably should have.

So this PR finally makes Opus mandatory. If the day comes when there's a system out there that /doesn't/ support Opus, then we can reconsider making it optional.  But I doubt that will happen :-)

(That's the personal side to this PR, the logical case for this PR is in the comment above)

2021-03-05 17:43 UTC, dreamer requested changes
Great change! :) One fewer optional dependency means smaller test matrix and less code.

Two additional changes are needed:

- Remove `use_opusfile` option from `meson_options.txt` file.
- Add a line about Opus dependency to minimum build dependencies in `BUILD.md`

2021-03-05 17:43 UTC, dreamer commented on src/libs/decoders/meson.build
> +  'opus.cpp',
Ah, this was the root cause for missing Opus support…

2021-03-05 17:43 UTC, dreamer commented on meson.build
> +                           static : ('opusfile' in static_libs_list))
Great :)

2021-03-05 18:01 UTC, kcgen commented
> Remove use_opusfile option from meson_options.txt file.
> Add a line about Opus dependency to minimum build dependencies in BUILD.md

Thanks for these @dreamer; both are in now.

2021-03-06 00:50 UTC, dreamer approved these changes
@kcgen Thanks!

2021-03-06 00:50 UTC, merged